# Site settings
title: "Sunny Juneja"
email: me@sunnyjuneja.com
author: Sunny Juneja
description: "Ideas and thoughts by Sunny Juneja."
baseurl: ""
url: "http://www.sunnyjuneja.com"
google_analytics: UA-46625863-1
animated: false
show_related_posts: false
show_post_footers: true

# Social icons
show_social_icons: false
github_username:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
